#pragma once

#define MAXIM186_CONFIG_CHANNEL_0 (0)
#define MAXIM186_CONFIG_CHANNEL_1 (4)
#define MAXIM186_CONFIG_CHANNEL_2 (1)
#define MAXIM186_CONFIG_CHANNEL_3 (5)
#define MAXIM186_CONFIG_CHANNEL_4 (2)
#define MAXIM186_CONFIG_CHANNEL_5 (6)
#define MAXIM186_CONFIG_CHANNEL_6 (3)
#define MAXIM186_CONFIG_CHANNEL_7 (7)

#define MAXIM186_CONFIG_POLARITY_BIPOLAR (0)
#define MAXIM186_CONFIG_POLARITY_UNIPOLAR (1)

#define MAXIM186_CONFIG_CONVERSION_TYPE_SINGLE_ENDED (1)
#define MAXIM186_CONFIG_CONVERSION_TYPE_DIFFERENTIAL (0)

#define MAXIM186_CONFIG_CLOCK_POWER_MODE_FULL_POWER_DOWN (0)
#define MAXIM186_CONFIG_CLOCK_POWER_MODE_FAST_POWER_DOWN (1)
#define MAXIM186_CONFIG_CLOCK_POWER_MODE_INTERNAL_CLOCK_MODE (2)
#define MAXIM186_CONFIG_CLOCK_POWER_MODE_EXTERNAL_CLOCK_MODE (3)
